### ISSUE TITLE
Higher-order component for p2panda state

### ISSUE THREAD

**Issue by adzialocha** [p2panda/beep-boop#14]
### Ideas

* `p2panda-js` should have a utility method like `getLibraryAsync` to load the library as a singleton because of its special dynamic import behaviour
* `PandaProvider` is a higher-order component (reference [ThemeProvider](https://github.com/mui-org/material-ui/blob/next/packages/material-ui-styles/src/ThemeProvider/ThemeProvider.js)) accepting user configuration as a prop. It loads the library via `getLibraryAsync`, generates the key pair when not given, creates a `Session` instance with the users configuration and exposes the library contents and session instance in `PandaContext`
* `PandaContext` is a react context initialized by `PandaProvider` and exposed to all of its child components (reference [ThemeContext](https://github.com/mui-org/material-ui/blob/next/packages/material-ui-styles/src/useTheme/ThemeContext.js))
* `useSession` is a hook (reference [useTheme](https://github.com/mui-org/material-ui/blob/next/packages/material-ui-styles/src/useTheme/useTheme.js)) taking the session instance out of the `PandaContext` and returning it
* `usePanda` is a hook similar to `useSession` returning the classes and methods of the `p2panda-js` library (sync)

### Draft examples

```jsx
<PandaProvider configuration={{ endpoint: 'wss://localhost:2022' }}>
  <App />
</PandaProvider>
```

```jsx
export default const App = () => {
  const session = useSession();
  const { Instance } = usePanda();
  
  const sendMessage = async (message) => {
    await Instance.create({ message }, { schema: CHAT_MESSAGE_SCHEMA, session });
  };

  // ...
};
```

### Open questions

- [ ] Is `PandaProvider`, `PandaContext`, `useSession` and `usePanda` part of `p2panda-js` or not?

@sophiiistika @cafca

**Comment by cafca** [comment]
Regarding the open question: we will probably publish some `p2panda-react` eventually, but let's keep it part of `beep-boop` until we have covered some ground.
